[package]
name = "tgs_t5_finetunned"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-bert = "0.21.0" # Check for the latest version
tch = "0.13"         # Torch library for Rust
