[package]
name = "tgs_bridge"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2"
numpy = "0.19"

[dependencies.pyo3]
version = "0.19.2"
features = ["auto-initialize"]

[features]
extension-module = ["pyo3/extension-module"]
default = ["extension-module"]
