[package]
name = "tgs"
version = "0.1.0"
authors = ["Lucas Oliveira <jucas.oliveira@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
